### ISSUE TITLE
 Bug with hide() paper-toast

### ISSUE THREAD

**Issue by tdesc** [PolymerElements/paper-toast#16] opened 2015-06-26 19:46 UTC
During paper-toast shown on screen hide() do nothing.

**Comment by ebidel** [comment] 2015-07-07 22:49
Do you have a test that repos this bug? I cannot reproduce it.

**Comment by pepperlk** [comment] 2015-09-15 01:55
I also have this.. The toast will show but not hide on hide() method

Toas is inside a template element. Will try to add more info.

**Comment by valdrinkoshi** [comment] 2015-11-30 19:54
tested with v1.1.1, and could not reproduce it. Closing this, please feel free to open it again with more details on how to reproduce it.

**Closed by valdrinkoshi** 2015-11-30 19:54 UTC
Labels: pending-response
