### ISSUE TITLE
Mobile A11y Testing 11/1

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-toast#32] opened 2015-11-02 16:05 UTC
On Android with Talkback, please note that when I click on the button to trigger each toast, the toast is then spoken aloud 3 times in a row. Any idea why this is the case? It's very redundant. :)

**Comment by valdrinkoshi** [comment] 2015-11-24 00:07
Closing this, as is a duplicate of https://github.com/PolymerElements/iron-a11y-announcer/issues/10

**Closed by valdrinkoshi** 2015-11-24 00:07 UTC
Labels: a11y
