### ISSUE TITLE
paper-toast does not scroll correctly when fitInto is set.

### ISSUE THREAD

**Issue by coreyfarrell** [PolymerElements/paper-toast#84] opened 2016-08-30 09:15 UTC
### Description
Setting a paper-toast to fit-bottom on a container should fix it's position relative to the container's viewport.

### Expected outcome
Scrolling the page with the toast shown should cause toast to 'stick' to the bottom of the container viewport.

### Actual outcome
Scrolling shows that the toast position is fixed relative to the document instead of being relative to the container.

### Live Demo
https://jsbin.com/tazivokatu/edit?html,output

Extracted from paper-toast standard demo page.

### Steps to reproduce
1. Click the 'Open Toast' button.
2. Scroll the page while the toast is displayed.
3. Observe that the toast does not move with `#container`

**Comment by valdrinkoshi** [comment] 2016-08-30 17:08
Hi @coreyfarrell, this looks like a duplicate of https://github.com/PolymerElements/iron-overlay-behavior/issues/140. The idea is to listen for scroll events and call `refit` on the overlay to position & fit it. Currently this is done in `iron-dropdown`, but it would be nice to move this feature to `iron-overlay-behavior` so that all overlays can benefit from it

**Closed by valdrinkoshi** 2016-08-30 17:08 UTC
