### ISSUE TITLE
paper-toast doesn't support center alignment

### ISSUE THREAD

**Issue by fejesjoco** [PolymerElements/paper-toast#83] opened 2016-08-22 21:03 UTC
According to the [material spec](https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-specs), a toast on desktop should be on the bottom center. ([Deep link for the image](https://material-design.storage.googleapis.com/publish/material_v_9/0B57Y8yNEHsZPRWxUaHo3bGNUeXM/components_toasts_tabletdesktop1.png).) It looks like paper-toast doesn't support it.

I tried be setting horizontalAlign='center' and 'middle', both result in an error to be thrown. I checked the docs, which refer to iron-fit-behavior, and it doesn't mention center or middle either, just left, right, and auto (auto doesn't center either). Finally I checked the [demo of iron-fit-behavior](https://elements.polymer-project.org/elements/iron-fit-behavior?view=demo:demo/index.html&active=Polymer.IronFitBehavior). Initially it is centered both horizontally and vertically, but when I press the 'bottom' button to go down, it also goes left or right and keeps jumping based on scroll position (which may be a bug as well), but it doesn't stay horizontally centered.

**Comment by ergo** [comment] 2016-08-24 12:11
bump

**Comment by valdrinkoshi** [comment] 2016-08-24 17:34
This issue is a duplicate of https://github.com/PolymerElements/iron-fit-behavior/issues/43, as `paper-toast` implements `iron-overlay-behavior` which implements `iron-fit-behavior`.
A temporary solution is to use [horizontalOffset](https://elements.polymer-project.org/elements/iron-fit-behavior#property-horizontalOffset) to push the toast to the center

**Comment by ergo** [comment] 2016-08-24 19:02
@valdrinkoshi It would be great if horizontalOffset would support percentage values instead of px.

**Comment by valdrinkoshi** [comment] 2016-08-24 19:27
You could just use the css `margin-left` property for that ;)
```css
    paper-toast {
      width: 300px;
      margin-left: calc(50vw - 150px);
    }

**Comment by ergo** [comment] 2016-08-24 21:00
@valdrinkoshi thanks! That was a good idea - will test tommorow.

**Comment by valdrinkoshi** [comment] 2016-08-24 21:11
Cool! will close this issue 👍

**Closed by valdrinkoshi** 2016-08-24 21:11 UTC

**Comment by bennypowers** [comment] 2017-03-16 13:57
FWIW I solved this with 

```html
<paper-toast vertical-align horizontal-align id="toast">
```
And in the event handler which opens the toast:
```js
this.$.toast.center();
this.$.toast.refit();
this.$.toast.open();
```
