### ISSUE TITLE
paper-toast inside custom element is not visible - only in chrome

### ISSUE THREAD

**Issue by ranjeet-choudhary** [PolymerElements/paper-toast#25] opened 2015-09-12 08:04 UTC
In firefox, its working fine.

it might be a chrome issue http://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform

**Comment by valdrinkoshi** [comment] 2015-11-18 02:22
Hi @ranjeet-choudhary, if you open the toast on your element's `attached` it works just fine, see here http://jsbin.com/notuvejele/edit?html,output
```html
  <dom-module id="x-foo">
    <style>
      :host {
        display: block;
        background-color: orange;
        width: 100px;
        height: 100px;
        overflow: hidden;
      }
    </style>
    <template>
      <div>x-foo</div>
      <paper-toast id='toast' text="toast" duration="10000"></paper-toast>
    </template>
    <script>
      Polymer({
        is: 'x-foo',
        attached: function(){
          this.$.toast.show();
        }
      });
    </script>
  </dom-module>
```

**Comment by valdrinkoshi** [comment] 2015-11-18 02:23
closing as i couldn't reproduce

**Closed by valdrinkoshi** 2015-11-18 02:23 UTC

**Comment by ranjeet-choudhary** [comment] 2015-11-18 14:47
@valdrinkoshi try putting toast in navigation drawer, issue is similar to this one https://github.com/PolymerElements/paper-toast/issues/14

**Comment by renfeng** [comment] 2018-02-08 02:12
@valdrinkoshi It should not be closed just because you could not reproduce it.
